# Generated by Django 5.2.16 on 2026-07-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["status"], name="request_status_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["due_date"], name="request_due_date_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["assignee", "status", "due_date"], name="req_asg_status_due_idx"
            ),
        ),
    ]
